//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toplanti_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Tab
    {
        public int LogID { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Sifre { get; set; }
    }
}
