//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toplanti_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Tab
    {
        public int ToplantiID { get; set; }
        public string Salon { get; set; }
        public Nullable<System.DateTime> Toplanti_Tarihi { get; set; }
        public string Toplanti_Adi { get; set; }
        public Nullable<System.TimeSpan> Toplanti_Baslangic_Saati { get; set; }
        public Nullable<System.TimeSpan> Toplanti_Bitis_Saati { get; set; }
        public string Konu { get; set; }
        public string Konuklar { get; set; }
    }
}
