//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toplanti_Takip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRUD_SP_DBEntities : DbContext
    {
        public CRUD_SP_DBEntities()
            : base("name=CRUD_SP_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login_Tab> Login_Tab { get; set; }
        public virtual DbSet<Meeting_Tab> Meeting_Tab { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
